insert_stm = """\
INSERT ALL
{}
SELECT * FROM dual;
"""

into_stm = """\
INTO {} ({}) VALUES ({})\
"""

from random import choice, randint, shuffle
from lorem.text import TextLorem
from itertools import product
from string import ascii_uppercase

def values_to_string(l):
    args = []
    for i in l:
        if type(i) is int or type(i) is float:
            args.append(str(i))
        elif type(i) is bool:
            args.append('1' if i else '0')
        elif type(i) is str:
            args.append("\'{}\'".format(i))

    return ', '.join(args)

def into(table, columns, args):
    return into_stm.format(table, ', '.join(columns), values_to_string(args))

def insert(table, columns, values):
    s = []
    for v in values:
        s.append(into(table, columns, v))

    return insert_stm.format('\n'.join(s))

def random_name(n = 4):
    lorem = TextLorem(wsep=' ', srange=(2,n))
    return lorem.sentence()[:-1].upper()

dollar_to_cents = 100

# holders - accounts - securitys - owns
def gen_hato(n, m):
    holders_values = [[
            ''.join([str(randint(0, 9)) for _ in range(9)]),
            random_name(),
            choice(['PERSON', 'COMPANY']),
            random_name(6),
            random_name(6),
            'company{}@email.com'.format(i),
            '+99-222-{}'.format(i),
        ] for i in range(n)]
    holders_values.insert(0, [
        '123456789',
        'FAKE STOCK EXCHANGE LTD.',
        'COMPANY',
        'MARIUS LACATUS NO. 7',
        'STEPHAN THE GREAT NO 1453',
        'michaeljackson@obama.gov',
        '07222222'
        ])
    stock_exchange_id = 1

    securitys_names = [random_name(5) for i in range(m)]
    securitys_values = [[
            ''.join([x for j, x in enumerate(securitys_names[i]) if j == 0 or securitys_names[i][j - 1] == ' ']),
            securitys_names[i],
            randint(10**3, 10**7),
            randint(1, 200) * dollar_to_cents,
            randint(1, 200) * dollar_to_cents,
            choice(['FUND_SECURITY', 'STOCK_SECURITY', 'BOND_SECURITY'])
        ] for i in range(m)]

    owns = [[
            stock_exchange_id,
            securitys_values[i][0],
            1,
        ] for i in range(m)]

    asks = [[
            'ASK',
            securitys_values[i][0],
            stock_exchange_id,
            securitys_values[i][2] - 1,
            securitys_values[i][3],
            securitys_values[i][2] - 1,
        ] for i in range(m)]


    stocks = [[x[0], choice(['COMMON', 'PREFERRED']), choice([0, 1])] for x in securitys_values if x[-1] == 'STOCK_SECURITY']
    funds = [[x[0], choice(['HEDGE', 'MUTUAL', 'BOND'])] for x in securitys_values if x[-1] == 'FUND_SECURITY']
    bonds = [[x[0], choice([0.05, 0.09, 0.1, 0.04])] for x in securitys_values if x[-1] == 'BOND_SECURITY']

    s = [
            insert('holder', [
            'legal_id',
            'legal_name',
            'legal_status',
            'physical_address',
            'billing_address',
            'email',
            'phone',
        ] , holders_values),

            insert('account', ['holder_id', 'capital'], [[holders_values[i][0],
                randint(10**3, 10**7) * dollar_to_cents
                ] for i in range(n + 1)]),

            insert('security', ['ticker', 'name', 'total_shares', 'last_ask_price','last_bid_price', 'type'], securitys_values),

            insert('own', ['account_id', 'ticker', 'amount'], owns),

            insert('quotation', ['type', 'ticker', 'account_id', 'amount', 'price', 'remaining'], asks),

            insert('stock_security', ['ticker','type', 'pays_dividents'], stocks) if len(stocks) else "",
            insert('bond_security', ['ticker','interest_rate'], bonds) if len(bonds) else "",
            insert('fund_security', ['ticker','type'], funds) if len(funds) else "",

        ]

    return "/**\n * WARNING: This file was generated. \n * Any modification you make will be lost.\n */\n\n" + '\n\n'.join(s)

from sys import argv

argc = len(argv)
n = int(argv[1]) if argc > 1 else 10
m = int(argv[2]) if argc > 2 else 30

print (gen_hato(n, m))
