/**
 * WARNING: This file was generated. 
 * Any modification you make will be lost.
 */

INSERT ALL
INTO holder (legal_id, legal_name, legal_status, physical_address, billing_address, email, phone) VALUES ('575563072', 'VELIT UT', 'COMPANY', 'NEQUE CONSECTETUR NUMQUAM', 'QUAERAT SIT', 'company0@email.com', '+99-222-0')
INTO holder (legal_id, legal_name, legal_status, physical_address, billing_address, email, phone) VALUES ('294692620', 'DOLORE QUAERAT QUISQUAM MAGNAM', 'PERSON', 'MODI NON QUISQUAM IPSUM PORRO IPSUM', 'VELIT VELIT', 'company1@email.com', '+99-222-1')
INTO holder (legal_id, legal_name, legal_status, physical_address, billing_address, email, phone) VALUES ('209418944', 'QUAERAT PORRO', 'COMPANY', 'MAGNAM PORRO NUMQUAM DOLOR CONSECTETUR IPSUM', 'DOLORE MODI UT IPSUM PORRO VOLUPTATEM', 'company2@email.com', '+99-222-2')
INTO holder (legal_id, legal_name, legal_status, physical_address, billing_address, email, phone) VALUES ('217102881', 'DOLOR DOLOR DOLORE', 'PERSON', 'NEQUE UT ALIQUAM', 'ALIQUAM MAGNAM AMET DOLOREM', 'company3@email.com', '+99-222-3')
INTO holder (legal_id, legal_name, legal_status, physical_address, billing_address, email, phone) VALUES ('201071784', 'DOLORE TEMPORA NON ADIPISCI', 'COMPANY', 'SED SED', 'DOLORE DOLOR EST PORRO', 'company4@email.com', '+99-222-4')
INTO holder (legal_id, legal_name, legal_status, physical_address, billing_address, email, phone) VALUES ('123456789', 'FAKE STOCK EXCHANGE LTD.', 'COMPANY', 'MARIUS LACATUS NO. 7', 'STEPHAN THE GREAT NO 1453', 'michaeljackson@obama.gov', '07222222')
SELECT * FROM dual;


INSERT ALL
INTO account (holder_id, capital) VALUES ('575563072', 41075900)
INTO account (holder_id, capital) VALUES ('294692620', 697142900)
INTO account (holder_id, capital) VALUES ('209418944', 124239000)
INTO account (holder_id, capital) VALUES ('217102881', 476749700)
INTO account (holder_id, capital) VALUES ('201071784', 947042800)
INTO account (holder_id, capital) VALUES ('123456789', 660820000)
SELECT * FROM dual;


INSERT ALL
INTO security (ticker, name, total_shares, last_price, type) VALUES ('QAEVV', 'QUAERAT AMET EST VELIT VOLUPTATEM', 3379597, 17500, 'BOND_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('TT', 'TEMPORA TEMPORA', 8374616, 8300, 'FUND_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('CA', 'CONSECTETUR AMET', 7687413, 10600, 'BOND_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('NQMA', 'NON QUISQUAM MODI ADIPISCI', 3597250, 1200, 'STOCK_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('AV', 'ADIPISCI VOLUPTATEM', 6173761, 10300, 'BOND_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('NQMP', 'NON QUIQUIA MAGNAM PORRO', 1171364, 13100, 'STOCK_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('CAMV', 'CONSECTETUR ADIPISCI MODI VOLUPTATEM', 1850275, 3500, 'FUND_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('NM', 'NEQUE MAGNAM', 540782, 8200, 'FUND_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('SESLP', 'SED EIUS SIT LABORE PORRO', 6963218, 3100, 'STOCK_SECURITY')
INTO security (ticker, name, total_shares, last_price, type) VALUES ('PME', 'PORRO MODI EST', 5902628, 15400, 'FUND_SECURITY')
SELECT * FROM dual;


INSERT ALL
INTO own (account_id, ticker, amount) VALUES (6, 'QAEVV', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'TT', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'CA', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'NQMA', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'AV', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'NQMP', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'CAMV', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'NM', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'SESLP', 1)
INTO own (account_id, ticker, amount) VALUES (6, 'PME', 1)
SELECT * FROM dual;


INSERT ALL
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'QAEVV', 6, 3379596, 17500)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'TT', 6, 8374615, 8300)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'CA', 6, 7687412, 10600)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'NQMA', 6, 3597249, 1200)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'AV', 6, 6173760, 10300)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'NQMP', 6, 1171363, 13100)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'CAMV', 6, 1850274, 3500)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'NM', 6, 540781, 8200)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'SESLP', 6, 6963217, 3100)
INTO quotation (type, ticker, account_id, amount, price) VALUES ('ASK', 'PME', 6, 5902627, 15400)
SELECT * FROM dual;


INSERT ALL
INTO stock_security (ticker, type, pays_dividents) VALUES ('NQMA', 'COMMON', 1)
INTO stock_security (ticker, type, pays_dividents) VALUES ('NQMP', 'PREFERRED', 0)
INTO stock_security (ticker, type, pays_dividents) VALUES ('SESLP', 'COMMON', 0)
SELECT * FROM dual;


INSERT ALL
INTO bond_security (ticker, interest_rate) VALUES ('QAEVV', 0.05)
INTO bond_security (ticker, interest_rate) VALUES ('CA', 0.09)
INTO bond_security (ticker, interest_rate) VALUES ('AV', 0.05)
SELECT * FROM dual;


INSERT ALL
INTO fund_security (ticker, type) VALUES ('TT', 'MUTUAL')
INTO fund_security (ticker, type) VALUES ('CAMV', 'MUTUAL')
INTO fund_security (ticker, type) VALUES ('NM', 'HEDGE')
INTO fund_security (ticker, type) VALUES ('PME', 'HEDGE')
SELECT * FROM dual;

